# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class McpSync < Formula
  desc "Manage and sync MCP servers across development tools"
  homepage "https://github.com/andre-carbajal/mcp-sync"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/andre-carbajal/mcp-sync/releases/download/v0.1.0/mcp-sync_0.1.0_darwin_amd64.tar.gz"
      sha256 "50a588799ec697381d293c95bedddfd65c0dd2c4dfbebe1be36935cc4d5108e5"

      define_method(:install) do
        bin.install "mcp-sync"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/andre-carbajal/mcp-sync/releases/download/v0.1.0/mcp-sync_0.1.0_darwin_arm64.tar.gz"
      sha256 "9becfbd769a8f57763ded3fa5b9dc03421ae7ba1428b0887343d31cfb3b5253d"

      define_method(:install) do
        bin.install "mcp-sync"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/andre-carbajal/mcp-sync/releases/download/v0.1.0/mcp-sync_0.1.0_linux_amd64.tar.gz"
      sha256 "cea2b7c4b6110eda1fa93bed7f8d20de74b8785432937149a637975c4aa2e5b2"
      define_method(:install) do
        bin.install "mcp-sync"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/andre-carbajal/mcp-sync/releases/download/v0.1.0/mcp-sync_0.1.0_linux_arm64.tar.gz"
      sha256 "eb5e38439a09c05e6a88242918a2a953ac14d0d74f28e75e231b259fc423d517"
      define_method(:install) do
        bin.install "mcp-sync"
      end
    end
  end
end
