# This file was generated by GoReleaser. DO NOT EDIT.
cask "goeverything" do
  version "2.2.4"

  on_macos do
    on_arm do
      sha256 "c8e3778c777e61c7e7f2c9db00b10f1d6e0c35ea6aa76ef8b2a725ff8dddcd8a"
      url "https://github.com/andre-carbajal/GoEverything/releases/download/v#{version}/goeverything_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "ba0331f09151f91da3856525366172cb5d11ae5b4dfc02972a9e70cf22fd73fb"
      url "https://github.com/andre-carbajal/GoEverything/releases/download/v#{version}/goeverything_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "9e5419bf8ccc3c0525e3e40496fef414e62af16f48150a8478225af055b84b3c"
      url "https://github.com/andre-carbajal/GoEverything/releases/download/v#{version}/goeverything_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "8db8d0abf5078799f6b3e93bcde9ef3b15b46bb93623ff2ebcb637e92edf1d46"
      url "https://github.com/andre-carbajal/GoEverything/releases/download/v#{version}/goeverything_#{version}_linux_amd64.tar.gz"
    end
  end

  name "goeverything"
  desc "Fast local file indexing and search"
  homepage "https://github.com/andre-carbajal/GoEverything"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ge"

  # No zap stanza required
end
