# This file was generated by GoReleaser. DO NOT EDIT.
cask "goeverything" do
  version "2.1.0"

  on_macos do
    on_intel do
      sha256 "e6b8ffd5bb2eef0ce85ca003bc4d6b3a969db3e9891363bb76ca27d982b6766a"
      url "https://github.com/andre-carbajal/GoEverything/releases/download/v#{version}/goeverything_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "2d33fcdb733f70df3251e8783721c0cbaf0bc53dfd1024da87d7e69d5f0c544c"
      url "https://github.com/andre-carbajal/GoEverything/releases/download/v#{version}/goeverything_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "goeverything"
  desc "Fast local file indexing and search"
  homepage "https://github.com/andre-carbajal/GoEverything"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ge"

  # No zap stanza required

end
