# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Goeverything < Formula
  desc "Fast local file indexing and search"
  homepage "https://github.com/andre-carbajal/GoEverything"
  version "2.0.0"
  license "GPL v3"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/andre-carbajal/GoEverything/releases/download/v2.0.0/goeverything_2.0.0_darwin_amd64.tar.gz"
    sha256 "112fd2318b098506ece23b0e16faa93b85671222535256341a7661c5a11fb661"

    define_method(:install) do
      bin.install "ge"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/andre-carbajal/GoEverything/releases/download/v2.0.0/goeverything_2.0.0_darwin_arm64.tar.gz"
    sha256 "75836759b80e8f5902216b5e956e89743adea62813f4364aef01a1fc7dc4c3e0"

    define_method(:install) do
      bin.install "ge"
    end
  end

  test do
    system "#{bin}/ge", "--help"
  end
end
