# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Goeverything < Formula
  desc "Fast local file indexing and search for macOS (Everything-style)"
  homepage "https://github.com/andre-carbajal/GoEverything"
  version "0.1.3"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/andre-carbajal/GoEverything/releases/download/v0.1.3/goeverything_0.1.3_darwin_amd64.tar.gz"
    sha256 "37b8914215431e36c623e4a11f69ed8a3b2e71d5bba70eb7930c3f5c94342361"

    define_method(:install) do
      bin.install "ge"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/andre-carbajal/GoEverything/releases/download/v0.1.3/goeverything_0.1.3_darwin_arm64.tar.gz"
    sha256 "8ae978fdbe0d6db8e469355dff3c4d4f1b41d3f028d511b69dcff2c82aed479f"

    define_method(:install) do
      bin.install "ge"
    end
  end

  test do
    system "#{bin}/ge", "--help"
  end
end
