# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class McpSync < Formula
  desc "Manage and sync MCP servers across development tools"
  homepage "https://github.com/andre-carbajal/mcp-sync"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/andre-carbajal/mcp-sync/releases/download/v0.1.1/mcp-sync_0.1.1_darwin_amd64.tar.gz"
      sha256 "5773fede95153b07c61501a0bb4f923c1ead733d958a2c11c26a2fb99e2f30eb"

      define_method(:install) do
        bin.install "mcp-sync"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/andre-carbajal/mcp-sync/releases/download/v0.1.1/mcp-sync_0.1.1_darwin_arm64.tar.gz"
      sha256 "6ff6484988eaa36bb064f8cd92e813581aa821d47c50e6b4868b49154620457a"

      define_method(:install) do
        bin.install "mcp-sync"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/andre-carbajal/mcp-sync/releases/download/v0.1.1/mcp-sync_0.1.1_linux_amd64.tar.gz"
      sha256 "d6063ee277db7219c01e1c1f710f8289787a42c088911a33a98b45ce9a44dcab"
      define_method(:install) do
        bin.install "mcp-sync"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/andre-carbajal/mcp-sync/releases/download/v0.1.1/mcp-sync_0.1.1_linux_arm64.tar.gz"
      sha256 "6f5163afe19d96f24aca16a0255d6c5f454c36264cbb5351169ecfd34494fd51"
      define_method(:install) do
        bin.install "mcp-sync"
      end
    end
  end
end
